Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Controllers/TenPayV3Controller.cs
/*----------------------------------------------------------------
    Copyright (C) 2016 Senparc
    
    文件名：TenPayV3Controller.cs
    文件功能描述：微信支付V3Controller
    
    
    创建标识：Senparc - 20150312
 
    修改标识：Senparc - 20150419
    修改描述：添加产品相关
----------------------------------------------------------------*/

using System;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Web.Mvc;
using System.Xml.Linq;
using Senparc.Weixin.BrowserUtility;
using Senparc.Weixin.MP.AdvancedAPIs;
using Senparc.Weixin.MP.AdvancedAPIs.OAuth;
using Senparc.Weixin.MP.Sample.Models;
using Senparc.Weixin.MP.TenPayLibV3;
using ZXing;
using ZXing.Common;

namespace Senparc.Weixin.MP.Sample.Controllers
{
    /// <summary>
    /// 根据官方的Webforms Demo改写，所以可以看到直接Response.Write()之类的用法，实际项目中不提倡这么做。
    /// </summary>
    public class TenPayV3Controller : Controller
    {
        private static TenPayV3Info _tenPayV3Info;

        private static bool CheckValidationResult(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors errors)
        {
            if (errors == SslPolicyErrors.None)
                return true;
            return false;
        }

        public static TenPayV3Info TenPayV3Info
        {
            get
            {
                if (_tenPayV3Info == null)
                {
                    _tenPayV3Info =
                        TenPayV3InfoCollection.Data[System.Configuration.ConfigurationManager.AppSettings["TenPayV3_MchId"]];
                }
                return _tenPayV3Info;
            }
        }

        /// <summary>
        /// 获取用户的OpenId
        /// </summary>
        /// <returns></returns>
        public ActionResult Index(int productId = 0, int hc = 0)
        {
            var returnUrl = string.Format("http://weixin.senparc.com/TenPayV3/JsApi");
            var state = string.Format("{0}|{1}", productId, hc);
            var url = OAuthApi.GetAuthorizeUrl(TenPayV3Info.AppId, returnUrl, state, OAuthScope.snsapi_userinfo);

            return Redirect(url);
        }

        #region JsApi支付

        public ActionResult JsApi(string code, string state)
        {
            if (string.IsNullOrEmpty(code))
            {
                return Content("您拒绝了授权！");
            }

            if (!state.Contains("|"))
            {
                //这里的state其实是会暴露给客户端的，验证能力很弱，这里只是演示一下
                //实际上可以存任何想传递的数据，比如用户ID，并且需要结合例如下面的Session["OAuthAccessToken"]进行验证
                return Content("验证失败！请从正规途径进入！1001");
            }

            //获取产品信息
            var stateData = state.Split('|');
            int productId = 0;
            ProductModel product = null;
            if (int.TryParse(stateData[0], out productId))
            {
                int hc = 0;
                if (int.TryParse(stateData[1], out hc))
                {
                    var products = ProductModel.GetFakeProductList();
                    product = products.FirstOrDefault(z => z.Id == productId);
                    if (product == null || product.GetHashCode() != hc)
                    {
                        return Content("商品信息不存在，或非法进入！1002");
                    }
                    ViewData["product"] = product;
                }
            }

            //通过，用code换取access_token
            var openIdResult = OAuthApi.GetAccessToken(TenPayV3Info.AppId, TenPayV3Info.AppSecret, code);
            if (openIdResult.errcode != ReturnCode.请求成功)
            {
                return Content("错误：" + openIdResult.errmsg);
            }

            string timeStamp = "";
            string nonceStr = "";
            string paySign = "";

            string sp_billno = Request["order_no"];
            //当前时间 yyyyMMdd
            string date = DateTime.Now.ToString("yyyyMMdd");

            if (null == sp_billno)
            {
                //生成订单10位序列号，此处用时间和随机数生成，商户根据自己调整，保证唯一
                sp_billno = DateTime.Now.ToString("HHmmss") + TenPayV3Util.BuildRandomStr(28);
            }
            else
            {
                sp_billno = Request["order_no"].ToString();
            }

            //创建支付应答对象
            RequestHandler packageReqHandler = new RequestHandler(null);
            //初始化
            packageReqHandler.Init();

            timeStamp = TenPayV3Util.GetTimestamp();
            nonceStr = TenPayV3Util.GetNoncestr();

            //设置package订单参数
            packageReqHandler.SetParameter("appid", TenPayV3Info.AppId);		  //公众账号ID
            packageReqHandler.SetParameter("mch_id", TenPayV3Info.MchId);		  //商户号
            packageReqHandler.SetParameter("nonce_str", nonceStr);                    //随机字符串
            packageReqHandler.SetParameter("body", product == null ? "test" : product.Name);    //商品信息
            packageReqHandler.SetParameter("out_trade_no", sp_billno);		//商家订单号
            packageReqHandler.SetParameter("total_fee", product == null ? "100" : (product.Price * 100).ToString());			        //商品金额,以分为单位(money * 100).ToString()
            packageReqHandler.SetParameter("spbill_create_ip", Request.UserHostAddress);   //用户的公网ip，不是商户服务器IP
            packageReqHandler.SetParameter("notify_url", TenPayV3Info.TenPayV3Notify);		    //接收财付通通知的URL
            packageReqHandler.SetParameter("trade_type", TenPayV3Type.JSAPI.ToString());	                    //交易类型
            packageReqHandler.SetParameter("openid", openIdResult.openid);	                    //用户的openId

            string sign = packageReqHandler.CreateMd5Sign("key", TenPayV3Info.Key);
            packageReqHandler.SetParameter("sign", sign);	                    //签名

            string data = packageReqHandler.ParseXML();

            var result = TenPayV3.Unifiedorder(data);
            var res = XDocument.Parse(result);
            string prepayId = res.Element("xml").Element("prepay_id").Value;

            //设置支付参数
            RequestHandler paySignReqHandler = new RequestHandler(null);
            paySignReqHandler.SetParameter("appId", TenPayV3Info.AppId);
            paySignReqHandler.SetParameter("timeStamp", timeStamp);
            paySignReqHandler.SetParameter("nonceStr", nonceStr);
            paySignReqHandler.SetParameter("package", string.Format("prepay_id={0}", prepayId));
            paySignReqHandler.SetParameter("signType", "MD5");
            paySign = paySignReqHandler.CreateMd5Sign("key", TenPayV3Info.Key);

            ViewData["appId"] = TenPayV3Info.AppId;
            ViewData["timeStamp"] = timeStamp;
            ViewData["nonceStr"] = nonceStr;
            ViewData["package"] = string.Format("prepay_id={0}", prepayId);
            ViewData["paySign"] = paySign;

            return View();
        }

        /// <summary>
        /// 原生支付 模式一
        /// </summary>
        /// <returns></returns>
        public ActionResult Native()
        {
            RequestHandler nativeHandler = new RequestHandler(null);
            string timeStamp = TenPayV3Util.GetTimestamp();
            string nonceStr = TenPayV3Util.GetNoncestr();

            //商品Id，用户自行定义
            string productId = DateTime.Now.ToString("yyyyMMddHHmmss");

            nativeHandler.SetParameter("appid", TenPayV3Info.AppId);
            nativeHandler.SetParameter("mch_id", TenPayV3Info.MchId);
            nativeHandler.SetParameter("time_stamp", timeStamp);
            nativeHandler.SetParameter("nonce_str", nonceStr);
            nativeHandler.SetParameter("product_id", productId);
            string sign = nativeHandler.CreateMd5Sign("key", TenPayV3Info.Key);

            var url = TenPayV3.NativePay(TenPayV3Info.AppId, timeStamp, TenPayV3Info.MchId, nonceStr, productId, sign);

            BitMatrix bitMatrix;
            bitMatrix = new MultiFormatWriter().encode(url, BarcodeFormat.QR_CODE, 600, 600);
            BarcodeWriter bw = new BarcodeWriter();

            var ms = new MemoryStream();
            var bitmap = bw.Write(bitMatrix);
            bitmap.Save(ms, ImageFormat.Png);
            //return File(ms, "image/png");
            ms.WriteTo(Response.OutputStream);
            Response.ContentType = "image/png";
            return null;
        }

        public ActionResult NativeNotifyUrl()
        {
            ResponseHandler resHandler = new ResponseHandler(null);

            //返回给微信的请求
            RequestHandler res = new RequestHandler(null);

            string openId = resHandler.GetParameter("openid");
            string productId = resHandler.GetParameter("product_id");

            if (openId == null || productId == null)
            {
                res.SetParameter("return_code", "FAIL");
                res.SetParameter("return_msg", "回调数据异常");
            }

            //创建支付应答对象
            RequestHandler packageReqHandler = new RequestHandler(null);

            var sp_billno = DateTime.Now.ToString("HHmmss") + TenPayV3Util.BuildRandomStr(28);
            var nonceStr = TenPayV3Util.GetNoncestr();

            //创建请求统一订单接口参数
            packageReqHandler.SetParameter("appid", TenPayV3Info.AppId);	
            packageReqHandler.SetParameter("mch_id", TenPayV3Info.MchId);	
            packageReqHandler.SetParameter("nonce_str", nonceStr);          
            packageReqHandler.SetParameter("body", "test");    
            packageReqHandler.SetParameter("out_trade_no", sp_billno);		
            packageReqHandler.SetParameter("total_fee", "1");			    
            packageReqHandler.SetParameter("spbill_create_ip", Request.UserHostAddress);
            packageReqHandler.SetParameter("notify_url", TenPayV3Info.TenPayV3Notify);
            packageReqHandler.SetParameter("trade_type", TenPayV3Type.NATIVE.ToString());
            packageReqHandler.SetParameter("openid", openId);	                    
            packageReqHandler.SetParameter("product_id", productId);

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Views/TenPayV3/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
        <title>微信支付测试跳转页</title>

    </head>
    <body>
        <div>
        </div>
    </body>
</html>

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Views/TenPayV3/JsApi.cshtml
@using Senparc.Weixin.MP.Sample.Models
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>公众号jsapi支付测试网页</title>
    <meta http-equiv="Content-Type" content="text/html; charset=GBK" />
    <script language="javascript" src="http://res.mail.qq.com/mmr/static/lib/js/jquery.js" type="text/javascript"></script>
    <script language="javascript" src="http://res.mail.qq.com/mmr/static/lib/js/lazyloadv3.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
            background: #eae9e6;
        }

        body, p, table, td, th {
            font-size: 14px;
            font-family: helvetica,Arial,Tahoma;
        }

        h1 {
            font-family: Baskerville,HelveticaNeue-Bold,helvetica,Arial,Tahoma;
        }

        a {
            text-decoration: none;
            color: #385487;
        }

        .product {
            font-size: 200%;
            color: #a5a5a5;
        }

        .title h1 {
            font-size: 22px;
            font-weight: bold;
            padding: 0;
            margin: 0;
            line-height: 1.2;
            color: #1f1f1f;
        }

        .title p {
            color: #aaa;
            font-size: 12px;
            margin: 5px 0 0;
            padding: 0;
            font-weight: bold;
        }

    </style>
    <script language="javascript" type="text/javascript">
        function auto_remove(img) {
            div = img.parentNode.parentNode; div.parentNode.removeChild(div);
            img.onerror = "";
            return true;
        }

        function changefont(fontsize) {
            if (fontsize < 1 || fontsize > 4) return;
            $('#content').removeClass().addClass('fontSize' + fontsize);
        }

        // 当微信内置浏览器完成内部初始化后会触发WeixinJSBridgeReady事件。
        document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
            //公众号支付
            jQuery('a#getBrandWCPayRequest').click(function (e) {
                WeixinJSBridge.invoke('getBrandWCPayRequest', {
                    "appId": "@ViewData["appId"]", //公众号名称，由商户传入
                    "timeStamp": "@ViewData["timeStamp"]", //时间戳
                    "nonceStr": "@ViewData["nonceStr"]", //随机串
                    "package": "@Html.Raw(ViewData["package"])",//扩展包
                    "signType": "MD5", //微信签名方式:MD5
                    "paySign": "@ViewData["paySign"]" //微信签名
                }, function (res) {

                    if (res.err_msg == "get_brand_wcpay_request:ok") {
                    }
                    // 使用以上方式判断前端返回,微信团队郑重提示：res.err_msg将在用户支付成功后返回ok，但并不保证它绝对可靠。
                    //因此微信团队建议，当收到ok返回时，向商户后台询问是否收到交易成功的通知，若收到通知，前端展示交易成功的界面；若此时未收到通知，商户后台主动调用查询订单接口，查询订单的当前状态，并反馈给前端展示相应的界面。
                });

            });

            WeixinJSBridge.log('yo~ ready.');

        }, false);
        if (jQuery) {
            jQuery(function () {

                var width = jQuery('body').width() * 0.87;
                jQuery('img').error(function () {
                    var self = jQuery(this);
                    var org = self.attr('data-original1');
                    self.attr("src", org);
                    self.error(function () {
                        auto_remove(this);
                    });
                });
                jQuery('img').each(function () {
                    var self = jQuery(this);
                    var w = self.css('width');
                    var h = self.css('height');
                    w = w.replace('px', '');
                    h = h.replace('px', '');
                    if (w <= width) {
                        return;
                    }
                    var new_w = width;
                    var new_h = Math.round(h * width / w);
                    self.css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                    self.parents('div.pic').css({ 'width': new_w + 'px', 'height': new_h + 'px' });
                });
            });
        }
    </script>
</head>
<body>
    <div class="WCPay">
        <a id="getBrandWCPayRequest" href="javascript:void(0);">
            @if (ViewData["product"] is ProductModel)
            {
                var product = (ProductModel)ViewData["product"];
                <div class="product">
                    您已选中产品：@product.Name<br />
                    单价：@product.Price.ToString("c")
                </div>
            }
            <h1 class="title">点击提交可体验微信支付</h1>
        </a>
    </div>
</body>
</html>

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Views/TenPayV3/PayNotifyUrl.cshtml
@{
    Layout = null;
}

<html>
<head>
    <title>PayNotifyUrl</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
    </form>
</body>
</html>

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Views/TenPayV3/ProductItem.cshtml
@model Senparc.Weixin.MP.Sample.Models.ProductModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>商品详情</title>
</head>
<body>
    <div>
        <h1>商品名称：@Model.Name</h1>
        <p>单价：@Model.Price.ToString("c")</p>
        <p>
            使用微信“扫一扫”下方二维码完成支付：<br />
            <img src="@Url.Action("ProductPayCode",new{productId=Model.Id,hc=Model.GetHashCode()})" width="300" />
        </p>
    </div>
</body>
</html>

Senparc.Weixin.MP.Sample/Senparc.Weixin.MP.Sample/Views/TenPayV3/ProductList.cshtml
@model List<Senparc.Weixin.MP.Sample.Models.ProductModel>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>产品列表</title>
    <style>
        ul#productList, ul#productList li {
            list-style: none;
            display: inline;
        }

            ul#productList li {
                border: 1px solid #008b8b;
                background: #c9ff94;
                padding: 30px;
                margin: 20px;
                overflow: hidden;
                float: left;
            }

                ul#productList li.br {
                    clear: left;
                }

                ul#productList li a {
                    text-decoration: none;
                    display: block;
                    overflow: hidden;
                    clear: both;
                }
    </style>
</head>
<body>
    <div>
        <ul id="productList">
            @for (int i = 0; i <= Model.Count - 1; i++)
            {
                var item = Model[i];
                <li class="@(i > 0 && i % 4==0 ? "br" : null)">
                    <a href="@Url.Action("ProductItem", "TenPayV3", new {productId = item.Id, hc = item.GetHashCode()})">
                        <h2>@item.Name</h2>
                        <p>@item.Price.ToString("c")</p>
                        <p>点击购买</p>
                    </a>
                </li>
            }
        </ul>
    </div>
</body>
</html>